'use strict';
// ============================================================================
// Fast feasibility search on ARBITRARY period lattices (sheared tori).
//
// A period lattice is any full-rank sublattice Lambda of Z^2 (translations
// (a,b) of the up/down triangle lattice). Every such lattice has a unique
// Hermite normal form basis {(P,0), (s,Q)} with P,Q >= 1, 0 <= s < P, and
// index N = P*Q. A Lambda-periodic tiling is exactly a valid assignment on
// the 2N cells of Z^2 x {up,down} / Lambda (Lemma 3.3's argument, unchanged).
// The existing torusFeasible() only ever checked s = 0.
//
// Search: MAC (maintained arc consistency) over 18-bit state bitmasks, with
// O(1) support lookups through split 9-bit tables, MRV branching, and a
// translation-symmetry cut at the root (see searchLattice). Same state set as
// solver.js (buildStates, incl. the validated reflection-redundancy removal).
//
// Also here: HNF normalization, the lattice rotation R (60 deg) and mirror T,
// orbit-representative enumeration, and an INDEPENDENT solution verifier that
// unfolds a found solution over a large explicit region and re-checks every
// adjacency with lattice.js's neighbor()/L()/bowtie() directly -- sharing none
// of the solver's precomputed tables or its index arithmetic.
// ============================================================================
const { L, bowtie, neighbor } = require('./lattice.js');
const { buildStates, buildAdjBitmasks } = require('./solver.js');
const { placementGroup } = require('./alphabet.js');

const UP_OFFSETS = [[0, 0], [1, 0], [0, 1]];
const DOWN_OFFSETS = [[0, 0], [-1, 0], [0, -1]];

// ---------------------------------------------------------------------------
// Lattice arithmetic
// ---------------------------------------------------------------------------
function mod(x, m) { return ((x % m) + m) % m; }
function gcd(a, b) { a = Math.abs(a); b = Math.abs(b); while (b) { [a, b] = [b, a % b]; } return a; }
function egcd(a, b) { // returns [g, x, y] with a*x + b*y = g = gcd(a,b) >= 0
  if (b === 0) return a >= 0 ? [a, 1, 0] : [-a, -1, 0];
  const [g, x, y] = egcd(b, a % b);
  return [g, y, x - Math.trunc(a / b) * y];
}

// Reduce (a,b) into the fundamental domain {0<=a<P, 0<=b<Q} of HNF(P,s,Q).
function reduceHNF(a, b, P, s, Q) {
  const j = Math.floor(b / Q);
  const bR = b - j * Q;
  const aR = mod(a - j * s, P);
  return [aR, bR];
}

// HNF of the lattice generated by two integer vectors (must be independent).
function hnfFromGenerators(v1, v2) {
  const [Q, x, y] = egcd(v1[1], v2[1]);
  if (Q === 0) throw new Error('degenerate lattice');
  const zx = x * v1[0] + y * v2[0];                 // (zx, Q) in Lambda
  const k0x = (v2[1] / Q) * v1[0] - (v1[1] / Q) * v2[0]; // (k0x, 0) generates Lambda ∩ (Z,0)
  const P = Math.abs(k0x);
  if (P === 0) throw new Error('degenerate lattice');
  return { P, s: mod(zx, P), Q, N: P * Q };
}

// 60-degree rotation of the triangular lattice in (a,b) coordinates:
// e1 -> e2, e2 -> e2 - e1, i.e. (a,b) -> (-b, a+b). Order 6; R^3 = -I acts
// trivially on lattices, so it generates a C_3 action on sublattices.
function rot(v) { return [-v[1], v[0] + v[1]]; }
// Mirror swapping e1 <-> e2 (preserves up/down; swaps edges 1 <-> 2).
function mir(v) { return [v[1], v[0]]; }

function transformLattice(lat, f) {
  return hnfFromGenerators(f([lat.P, 0]), f([lat.s, lat.Q]));
}
function latKey(l) { return `${l.P},${l.s},${l.Q}`; }

// All HNF lattices of index exactly N.
function hnfOfIndex(N) {
  const out = [];
  for (let P = 1; P <= N; P++) {
    if (N % P) continue;
    const Q = N / P;
    for (let s = 0; s < P; s++) out.push({ P, s, Q, N });
  }
  return out;
}

// Orbit representatives of HNF lattices with index in [minN, maxN] under the
// lattice point group: C_6 always (every tile may be rotated), D_6 when
// withMirror (valid only when EVERY tile is reflectable -- mirroring the
// whole tiling reflects every tile). Returns [{P,s,Q,N, orbitSize}], sorted
// by index, then by P (fewer columns first).
function latticeOrbitReps(minN, maxN, withMirror) {
  const reps = [];
  for (let N = minN; N <= maxN; N++) {
    const seen = new Set();
    for (const lat of hnfOfIndex(N)) {
      const k = latKey(lat);
      if (seen.has(k)) continue;
      // BFS closure of the orbit
      const orbit = new Map([[k, lat]]);
      const stack = [lat];
      while (stack.length) {
        const cur = stack.pop();
        const imgs = [transformLattice(cur, rot)];
        if (withMirror) imgs.push(transformLattice(cur, mir));
        for (const im of imgs) {
          const ik = latKey(im);
          if (!orbit.has(ik)) { orbit.set(ik, im); stack.push(im); }
        }
      }
      for (const ok of orbit.keys()) seen.add(ok);
      // representative: prefer smallest P (cheapest-looking), then smallest s
      const members = [...orbit.values()].sort((x, y) => (x.P - y.P) || (x.s - y.s));
      reps.push({ ...members[0], orbitSize: orbit.size });
    }
  }
  return reps;
}

// ---------------------------------------------------------------------------
// Torus graph for a lattice (tileset-independent; cache and reuse)
// ---------------------------------------------------------------------------
// Cell index: (aR*Q + bR)*2 + slot. For each cell, 3 arcs (nbrCell, edge).
const graphCache = new Map();
function torusGraph(P, s, Q) {
  const key = `${P},${s},${Q}`;
  let g = graphCache.get(key);
  if (g) return g;
  const NC = P * Q * 2;
  const nbr = new Int32Array(NC * 3);
  for (let a = 0; a < P; a++) for (let b = 0; b < Q; b++) for (let sl = 0; sl < 2; sl++) {
    const c = (a * Q + b) * 2 + sl;
    const offs = sl === 0 ? UP_OFFSETS : DOWN_OFFSETS;
    for (let e = 0; e < 3; e++) {
      const [aR, bR] = reduceHNF(a + offs[e][0], b + offs[e][1], P, s, Q);
      nbr[c * 3 + e] = (aR * Q + bR) * 2 + (1 - sl);
    }
  }
  g = { P, s, Q, NC, nbr };
  if (graphCache.size > 5000) graphCache.clear();
  graphCache.set(key, g);
  return g;
}

// ---------------------------------------------------------------------------
// Per-tileset compiled constraint tables (build once, reuse across lattices)
// ---------------------------------------------------------------------------
function compileTileset(tiles, reflectableFlags) {
  const states = buildStates(tiles, reflectableFlags);
  const { upToDown, downToUp, NS } = buildAdjBitmasks(tiles, states);
  if (NS > 30) throw new Error('too many states for 32-bit masks');
  // Split support tables: sup(e, D) = lo[e][D & 511] | hi[e][D >>> 9]
  const mk = (table) => {
    const lo = [], hi = [];
    for (let e = 0; e < 3; e++) {
      const L0 = new Int32Array(512), H0 = new Int32Array(512);
      for (let m = 1; m < 512; m++) {
        const low = m & -m, i = 31 - Math.clz32(low);
        L0[m] = L0[m ^ low] | (i < NS ? table[e][i] : 0);
        H0[m] = H0[m ^ low] | (i + 9 < NS ? table[e][i + 9] : 0);
      }
      lo.push(L0); hi.push(H0);
    }
    return { lo, hi };
  };
  return {
    tiles, reflectableFlags, states, NS,
    FULL: NS >= 31 ? 0x7fffffff : (1 << NS) - 1,
    supFromUp: mk(upToDown),   // up cell domain -> allowed states of its down nbr
    supFromDown: mk(downToUp), // down cell domain -> allowed states of its up nbr
  };
}

function popcount(x) {
  x = x - ((x >>> 1) & 0x55555555);
  x = (x & 0x33333333) + ((x >>> 2) & 0x33333333);
  return (((x + (x >>> 4)) & 0x0f0f0f0f) * 0x01010101) >>> 24;
}

// ---------------------------------------------------------------------------
// MAC search on one lattice.
// Returns { result: true|false|'unknown', nodes, solution?: Int32Array(state per cell) }
// ---------------------------------------------------------------------------
function searchLattice(ct, lat, opts = {}) {
  const budget = opts.budget || 2_000_000;
  const deadline = opts.timeoutMs ? Date.now() + opts.timeoutMs : 0;
  const { P, s, Q } = lat;
  const G = torusGraph(P, s, Q);
  const NC = G.NC, nbr = G.nbr;
  const { supFromUp, supFromDown, FULL } = ct;
  const uLo = supFromUp.lo, uHi = supFromUp.hi, dLo = supFromDown.lo, dHi = supFromDown.hi;

  const dom = new Int32Array(NC).fill(FULL);
  const trailCell = new Int32Array(NC * 64 + 1024), trailVal = new Int32Array(NC * 64 + 1024);
  let trailLen = 0;
  let trailCap = trailCell.length;
  let tC = trailCell, tV = trailVal;
  const queue = new Int32Array(NC), inQ = new Uint8Array(NC);
  let qLen = 0;

  function setDom(c, v) {
    if (trailLen === trailCap) { // grow
      const nc = new Int32Array(trailCap * 2), nv = new Int32Array(trailCap * 2);
      nc.set(tC); nv.set(tV); tC = nc; tV = nv; trailCap *= 2;
    }
    tC[trailLen] = c; tV[trailLen] = dom[c]; trailLen++;
    dom[c] = v;
  }
  function undoTo(mark) {
    while (trailLen > mark) { trailLen--; dom[tC[trailLen]] = tV[trailLen]; }
  }
  function enqueue(c) { if (!inQ[c]) { inQ[c] = 1; queue[qLen++] = c; } }
  function clearQueue() { while (qLen > 0) inQ[queue[--qLen]] = 0; }

  // AC propagation from everything in the queue. false = wipeout.
  function propagate() {
    while (qLen > 0) {
      const c = queue[--qLen]; inQ[c] = 0;
      const D = dom[c];
      const up = (c & 1) === 0;
      const base = c * 3;
      for (let e = 0; e < 3; e++) {
        const d = nbr[base + e];
        const allowed = up ? (uLo[e][D & 511] | uHi[e][D >>> 9]) : (dLo[e][D & 511] | dHi[e][D >>> 9]);
        const old = dom[d];
        const nd = old & allowed;
        if (nd !== old) {
          if (nd === 0) { clearQueue(); return false; }
          setDom(d, nd);
          enqueue(d);
        }
      }
    }
    return true;
  }

  let nodes = 0, bailed = false;
  function pickCell() {
    let best = -1, bestCnt = 99;
    for (let c = 0; c < NC; c++) {
      const D = dom[c];
      if ((D & (D - 1)) === 0) continue; // singleton
      const k = popcount(D);
      if (k < bestCnt) { bestCnt = k; best = c; if (k === 2) break; }
    }
    return best;
  }
  function dfs() {
    if (bailed) return false;
    nodes++;
    if (nodes > budget) { bailed = true; return false; }
    if (deadline && (nodes & 1023) === 0 && Date.now() > deadline) { bailed = true; return false; }
    const c = pickCell();
    if (c === -1) return true;
    let D = dom[c];
    while (D) {
      const bit = D & -D; D ^= bit;
      const mark = trailLen;
      setDom(c, bit); enqueue(c);
      if (propagate() && dfs()) return true;
      undoTo(mark);
      if (bailed) return false;
    }
    return false;
  }

  // Root: initial AC over all cells.
  for (let c = 0; c < NC; c++) enqueue(c);
  if (!propagate()) return { result: false, nodes: 1 };

  // Translation-symmetry cut. All up cells are equivalent under the torus's
  // translation group (it acts transitively), likewise all down cells. So if
  // no solution puts state x at root cell c0 (an up cell), no solution puts x
  // at ANY up cell: after refuting x at c0, delete x from every up cell.
  // Sound because any solution with x at up cell c translates to one with x
  // at c0.
  const c0 = 0; // up cell (0,0)
  let D0 = dom[c0];
  while (D0) {
    const bit = D0 & -D0; D0 ^= bit;
    if (!(dom[c0] & bit)) continue; // already eliminated by earlier cuts
    const mark = trailLen;
    setDom(c0, bit); enqueue(c0);
    nodes++;
    if (propagate() && dfs()) {
      return { result: true, nodes, solution: Int32Array.from(dom, d => 31 - Math.clz32(d)) };
    }
    undoTo(mark);
    if (bailed) return { result: 'unknown', nodes };
    // x refuted at c0 => refuted at all up cells.
    for (let c = 0; c < NC; c += 2) {
      if (dom[c] & bit) {
        const nd = dom[c] & ~bit;
        if (nd === 0) return { result: false, nodes };
        setDom(c, nd); enqueue(c);
      }
    }
    if (!propagate()) return { result: false, nodes };
  }
  return { result: false, nodes };
}

// ---------------------------------------------------------------------------
// Independent verification of a solution. Deliberately does NOT use the
// solver's graph, tables, or HNF index arithmetic: it builds an explicit
// region of (reps*P + 2) x (reps*Q + 2 + |shear-extent|) cells, assigns every
// cell by reducing it into the fundamental domain via a SEPARATE routine
// (solving for integer coefficients directly), then checks every in-region
// adjacency using lattice.js's neighbor(), L() and bowtie(). Also checks each
// placement is allowed by the tile's reflectability.
// ---------------------------------------------------------------------------
function verifyPeriodicSolution(tiles, reflectableFlags, lat, domainAssign) {
  // domainAssign: Map "a,b,slot" -> {tile, g} for 0<=a<P, 0<=b<Q
  const { P, s, Q } = lat;
  for (const [k, v] of domainAssign) {
    if (!placementGroup(reflectableFlags[v.tile]).includes(v.g)) return { ok: false, why: `disallowed placement at ${k}` };
  }
  // Independent reduction: (a,b) = i*(P,0) + j*(s,Q) + (aR,bR); j = floor(b/Q)
  // computed by repeated subtraction logic (different from reduceHNF's code path).
  function fund(a, b) {
    let j = 0; while (b - j * Q >= Q) j++; while (b - j * Q < 0) j--;
    const bR = b - j * Q;
    let ar = a - j * s; ar = ar - P * Math.floor(ar / P);
    return [ar, bR];
  }
  const W = 3 * P + 3, H = 3 * Q + 3;
  let checked = 0;
  for (let a = -2; a < W; a++) for (let b = -2; b < H; b++) for (let sl = 0; sl < 2; sl++) {
    const [fa, fb] = fund(a, b);
    const here = domainAssign.get(`${fa},${fb},${sl}`);
    if (!here) return { ok: false, why: `missing domain cell ${fa},${fb},${sl}` };
    for (let e = 0; e < 3; e++) {
      const [na, nb, ns] = neighbor(a, b, sl, e);
      const [ga, gb] = fund(na, nb);
      const there = domainAssign.get(`${ga},${gb},${ns}`);
      const lh = L(tiles[here.tile], here.g, e, sl);
      const lt = L(tiles[there.tile], there.g, e, ns);
      if (!bowtie(lh, lt)) return { ok: false, why: `mismatch at (${a},${b},${sl}) edge ${e}` };
      checked++;
    }
  }
  // Periodicity sanity: the assignment function is invariant under both generators.
  for (let a = 0; a < P; a++) for (let b = 0; b < Q; b++) {
    const f1 = fund(a + P, b), f2 = fund(a + s, b + Q), f0 = fund(a, b);
    if (f1[0] !== f0[0] || f1[1] !== f0[1] || f2[0] !== f0[0] || f2[1] !== f0[1]) return { ok: false, why: 'reduction not lattice-invariant' };
  }
  return { ok: true, edgesChecked: checked };
}

function solutionToDomain(ct, lat, solution) {
  const { P, Q } = lat;
  const domain = [], map = new Map();
  for (let a = 0; a < P; a++) for (let b = 0; b < Q; b++) for (let sl = 0; sl < 2; sl++) {
    const st = ct.states[solution[(a * Q + b) * 2 + sl]];
    domain.push({ a, b, slot: sl === 0 ? 'up' : 'down', tile: st.tileIndex, orientation: st.g });
    map.set(`${a},${b},${sl}`, { tile: st.tileIndex, g: st.g });
  }
  return { domain, map };
}

module.exports = {
  reduceHNF, hnfFromGenerators, rot, mir, transformLattice, latKey, hnfOfIndex,
  latticeOrbitReps, torusGraph, compileTileset, searchLattice,
  verifyPeriodicSolution, solutionToDomain, gcd,
};
